export const jobTitles = [
  ".Net Developer",
  "Android Developer",
  "AI Developer",
  "AI Engineer",
  "Applied Scientist",
  "Applied Data Scientist",
  "Applied AI Scientist",
  "Application Developer",
  "Artificial Intelligent Developer",
  "Artificial Intelligent Engineer",
  "Asp.Net Developer",
  "Associate Software Engineer",
  "AWS Developer",
  "Azure Developer",
  "Big Data Engineer",
  "Bioinformatician",
  "Bioinformatics",
  "Blockchain Developer",
  "Business Intelligence Developer",
  "C Developer",
  "C# Developer",
  "C++ Developer",
  "Central Office Technician",
  "Computer Scientist",
  "Computer Vision Engineer",
  "Crm Developer",
  "Dart Developer",
  "Data Administrator",
  "Data Analyst",
  "Data Engineer",
  "Data Scientist",
  "Desktop Publisher",
  "Development Engineer",
  "Director Of Software Engineering",
  "Dot Net Developer",
  "Drupal Developer",
  "Entry Level Developer",
  "Firmware Engineer",
  "Fpga Engineer",
  "Front End Developer",
  "Front End Engineer",
  "Front End Web Developer",
  "Full Stack Developer",
  "Game Developer",
  "Go Developer",
  "Golang Developer",
  "Haskell Developer",
  "Integration Architect",
  "Ios Developer",
  "J2Ee Developer",
  "Java",
  "Java Architect",
  "Java Consultant",
  "Java Developer",
  "Java Engineer",
  "Java Programmer",
  "Java Software Developer",
  "Java Software Engineer",
  "Java Web Developer",
  "Javascript Developer",
  "Junior Developer",
  "Junior Java Developer",
  "Junior Software Developer",
  "Junior Software Engineer",
  "Lua Developer",
  "Lead Developer",
  "Lead Engineer",
  "Lead Software Engineer",
  "Matlab Engineer",
  "ML Engineer",
  "Machine Learning Engineer",
  "Mobile Application Developer",
  "Mobile Developer",
  "Netsuite Consultant",
  "Node Developer",
  "Penetration Tester",
  "Peoplesoft Developer",
  "Perl Developer",
  "Php Developer",
  "Php Web Developer",
  "Platform Engineer",
  "Principal Software Engineer",
  "Process Development Engineer",
  "Process Technician",
  "Production Technician",
  "Programmer",
  "Programmer Analyst",
  "Python Developer",
  "R Developer",
  "React Developer",
  "React Native Developer",
  "Rails Developer",
  "Release Engineer",
  "Release Manager",
  "Ruby Developer",
  "Ruby on Rails Developer",
  "Rust Developer",
  "Salesforce Developer",
  "Sap Abap Developer",
  "Scrum Master",
  "Senior Programmer",
  "Senior Software Developer",
  "Senior Software Engineer",
  "Senior Web Developer",
  "Sharepoint Administrator",
  "Siebel Developer",
  "Software Analyst",
  "Software Architect",
  "Software Consultant",
  "Software Developer",
  "Software Development Engineer",
  "Software Development Manager",
  "Software Engineering Manager",
  "Software Manager",
  "Software Programmer",
  "Software Support Engineer",
  "Software Trainer",
  "Solidity Developer",
  "Spark Developer",
  "Staff Engineer",
  "Swift Developer",
  "Technical Architect",
  "Technical Consultant",
  "Technical Manager",
  "Unity Developer",
  "Unreal Engine Developer",
  "Vp Engineering",
  "Web Analyst",
  "Web Application Developer",
  "Web Architect",
  "Web Developer",
  "Web Programmer",
  "Website Administrator",
];
